AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions EventsRole and EventsRule resources to send CloudTrail events to Fugue's event bus
Parameters:
  EventBusArn:
    Type: String
    Description: Fugue event bus ARN
Resources:
  FugueEventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SendEvents
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Ref EventBusArn
  FugueEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Fugue Events Rule
      RoleArn: !GetAtt FugueEventsRole.Arn
      EventPattern:
        source:
          - "aws.acm"
          - "aws.apigateway"
          - "aws.apigatewayv2"
          - "aws.athena"
          - "aws.autoscaling"
          - "aws.cloudformation"
          - "aws.cloudfront"
          - "aws.cloudtrail"
          - "aws.cloudwatch"
          - "aws.codedeploy"
          - "aws.cognito-identity"
          - "aws.cognito-idp"
          - "aws.cognito-sync"
          - "aws.config"
          - "aws.dynamodb"
          - "aws.ec2"
          - "aws.ecr"
          - "aws.ecs"
          - "aws.eks"
          - "aws.elasticache"
          - "aws.elasticloadbalancing"
          - "aws.es"
          - "aws.fargate"
          - "aws.firehose"
          - "aws.glacier"
          - "aws.glue"
          - "aws.guardduty"
          - "aws.iam"
          - "aws.kinesis"
          - "aws.lambda"
          - "aws.macie"
          - "aws.organizations"
          - "aws.rds"
          - "aws.redshift"
          - "aws.route53"
          - "aws.s3"
          - "aws.sagemaker"
          - "aws.secretsmanager"
          - "aws.securityhub"
          - "aws.signin"
          - "aws.sns"
          - "aws.sqs"
          - "aws.states"
          - "aws.tag"
          - "aws.trustedadvisor"
          - "aws.waf"
          # - "aws.kms"
          # - "aws.logs"
          # - "aws.ssm"
        detail-type:
          - "AWS API Call via CloudTrail"
          - "AWS Console Sign In via CloudTrail"
          - "AWS Service Event via CloudTrail"
      State: "ENABLED"
      Targets:
        - Arn: !Ref EventBusArn
          Id: "TargetEventBus"